plugins {
    id 'java'
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
    id("xyz.jpenilla.run-paper") version "3.0.2"
}

group = 'dev.cabotmc'
version = '1.0'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven { url "https://repo.dmulloy2.net/repository/public/" }
    maven { url "https://maven.citizensnpcs.co/repo" }
    maven { url "https://repo.alessiodp.com/releases/"}
    maven {
        url "https://maven.enginehub.org/repo/"
    }
}

dependencies {
    compileOnly 'com.comphenix.protocol:ProtocolLib:5.3.0'
    paperweight.paperDevBundle("26.2.build.60-beta")
    compileOnly 'net.citizensnpcs:citizens-main:2.0.42-SNAPSHOT'
    compileOnly 'com.sk89q.worldedit:worldedit-bukkit:7.4.0'
}

configurations.all {
    resolutionStrategy {
        force("com.google.code.gson:gson:2.14.0")
        force("com.google.guava:guava:33.6.0-jre")
    }
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks {
    runServer {
        jvmArgs("-Dcom.mojang.eula.agree=true")
        minecraftVersion("26.2")
        downloadPlugins {
            //url("https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar")
            //url("https://ci.citizensnpcs.co/job/citizens2/4160/artifact/dist/target/Citizens-2.0.42-b4160.jar")
            //url("https://cdn.modrinth.com/data/1u6JkXh5/versions/p8T2aZ8U/worldedit-bukkit-7.4.2.jar")
        }
    }
}
