name: CabotEnchants
version: '${version}'
main: dev.cabotmc.cabotenchants.CabotEnchants
api-version: '1.20'
load: STARTUP
depend:
  - ProtocolLib
commands:
  givequestitem:
    description: Gives a quest item to a player
    usage: /givequestitem <quest id> <step id>
    permission: cabotenchants.givequestitem