name: CabotEnchants
version: '${version}'
main: dev.cabotmc.cabotenchants.CabotEnchants
api-version: '1.20'
load: STARTUP
depend:
  - ProtocolLib
commands:
  givequestitem:
    description: Gives a quest item to a player
    usage: /givequestitem <quest id> <step id>
    permission: cabotenchants.givequestitem
  cereload:
    description: Reloads the plugin
    usage: /cereload
    permission: cabotenchants.reload
  cosmetics:
    description: Opens the cosmetics menu
    usage: /cosmetics
    permission: cabot.enchants.cosmetics
  cosmeticunlock:
    description: Unlocks a cosmetic
    usage: /cosmeticunlock <cosmetic id>
    permission: cabot.enchants.unlock
